<?php

namespace SimpleMehanizm\Http\Protocol\FastCGI;

enum ServerKeys: string
{
    case REQUEST_METHOD = 'REQUEST_METHOD';
    case REQUEST_URI = 'REQUEST_URI';
    case HOSTNAME = 'HOSTNAME';
    case PHP_INI_DIR = 'PHP_INI_DIR';
    case PHP_LDFLAGS = 'PHP_LDFLAGS';
    case PHP_CFLAGS = 'PHP_CFLAGS';
    case PHP_VERSION = 'PHP_VERSION';
    case GPG_KEYS = 'GPG_KEYS';
    case PHP_CPPFLAGS = 'PHP_CPPFLAGS';
    case PHP_ASC_URL = 'PHP_ASC_URL';
    case PHP_URL = 'PHP_URL';
    case PATH = 'PATH';
    case PHP_SHA256 = 'PHP_SHA256';
    case USER = 'USER';
    case HTTP_ACCEPT_LANGUAGE = 'HTTP_ACCEPT_LANGUAGE';
    case HTTP_ACCEPT_ENCODING = 'HTTP_ACCEPT_ENCODING';
    case HTTP_SEC_FETCH_DEST = 'HTTP_SEC_FETCH_DEST';
    case HTTP_SEC_FETCH_USER = 'HTTP_SEC_FETCH_USER';
    case HTTP_SEC_FETCH_MODE = 'HTTP_SEC_FETCH_MODE';
    case HTTP_SEC_FETCH_SITE = 'HTTP_SEC_FETCH_SITE';
    case HTTP_ACCEPT = 'HTTP_ACCEPT';
    case HTTP_USER_AGENT = 'HTTP_USER_AGENT';
    case HTTP_UPGRADE_INSECURE_REQUESTS = 'HTTP_UPGRADE_INSECURE_REQUESTS';
    case HTTP_SEC_CH_UA_PLATFORM = 'HTTP_SEC_CH_UA_PLATFORM';
    case HTTP_SEC_CH_UA_MOBILE = 'HTTP_SEC_CH_UA_MOBILE';
    case HTTP_SEC_CH_UA = 'HTTP_SEC_CH_UA';
    case HTTP_CACHE_CONTROL = 'HTTP_CACHE_CONTROL';
    case HTTP_CONNECTION = 'HTTP_CONNECTION';
    case HTTP_HOST = 'HTTP_HOST';
    case REDIRECT_STATUS = 'REDIRECT_STATUS';
    case SERVER_NAME = 'SERVER_NAME';
    case SERVER_PORT = 'SERVER_PORT';
    case SERVER_ADDR = 'SERVER_ADDR';
    case REMOTE_PORT = 'REMOTE_PORT';
    case REMOTE_ADDR = 'REMOTE_ADDR';
    case SERVER_SOFTWARE = 'SERVER_SOFTWARE';
    case GATEWAY_INTERFACE = 'GATEWAY_INTERFACE';
    case REQUEST_SCHEME = 'REQUEST_SCHEME';
    case SERVER_PROTOCOL = 'SERVER_PROTOCOL';
    case DOCUMENT_ROOT = 'DOCUMENT_ROOT';
    case DOCUMENT_URI = 'DOCUMENT_URI';
    case SCRIPT_NAME = 'SCRIPT_NAME';
    case CONTENT_LENGTH = 'CONTENT_LENGTH';
    case CONTENT_TYPE = 'CONTENT_TYPE';
    case QUERY_STRING = 'QUERY_STRING';
    case SCRIPT_FILENAME = 'SCRIPT_FILENAME';
    case FCGI_ROLE = 'FCGI_ROLE';
    case PHP_SELF = 'PHP_SELF';
    case REQUEST_TIME_FLOAT = 'REQUEST_TIME_FLOAT';
    case REQUEST_TIME = 'REQUEST_TIME';
}